---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: course-testing-org/wordsmith-api
    newName: ghcr.io/course-testing-org/wordsmith-api
    newTag: stable-20230719-5a05485
  - name: course-testing-org/wordsmith-web
    newName: ghcr.io/course-testing-org/wordsmith-web
    newTag: stable-20230719-8d38f0f
configMapGenerator:
  - name: db-schema
    files:
      - words.sql
