---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: course-testing-org/wordsmith-api
    newName: ghcr.io/course-testing-org/wordsmith-api
    newTag: stable-20230719-f8ca9b0
  - name: course-testing-org/wordsmith-web
    newName: ghcr.io/course-testing-org/wordsmith-web
    newTag: stable-20230714-54a6571
configMapGenerator:
  - name: db-schema
    files:
      - words.sql
